Repository fluxcd/source-controller, pull requests merged in 2020-07, with the labels that each got.

#72 Move Receiver API to notification controller
  docs/spec/v1alpha1/README.md
  docs/spec/v1alpha1/receivers.md
Labels: area/docs

#78 Add ignore field to GitRepository spec
  api/v1alpha1/gitrepository_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/source.fluxcd.io_gitrepositories.yaml
  controllers/storage.go
  controllers/storage_test.go
  docs/api/source.md
  docs/spec/v1alpha1/gitrepositories.md
Labels: area/docs, area/git

#81 Fix artifact test server
  pkg/testserver/artifact.go
Labels: bug

#82 Add constants for kind names
  api/v1alpha1/gitrepository_types.go
  api/v1alpha1/helmchart_types.go
  api/v1alpha1/helmrepository_types.go
  controllers/suite_test.go
  main.go
Labels: enhancement

#84 Setup production logging
  config/manager/deployment.yaml
  go.mod
  main.go
Labels: enhancement

#88 Use Docker organization secrets in build
  .github/workflows/release.yml
Labels: area/build

#89 Improve error handling and reporting
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
Labels: enhancement

#90 Storage: fix a small bug in RemoveAllButCurrent when the directory is invalid
  controllers/storage.go
  controllers/storage_test.go
Labels: bug

#91 Remove HelmRepository owner ref on HelmChart
  controllers/helmchart_controller.go
Labels: area/helm, enhancement

#92 Refactor garbage collectors to finalizers
  api/v1alpha1/condition_types.go
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
  controllers/predicate.go
  controllers/util.go
Labels: enhancement

#95 Upgrade CRDs to apiextensions.k8s.io/v1
  .github/workflows/e2e.yaml
  Dockerfile
  Makefile
  config/crd/bases/source.fluxcd.io_gitrepositories.yaml
  config/crd/bases/source.fluxcd.io_helmcharts.yaml
  config/crd/bases/source.fluxcd.io_helmrepositories.yaml
  go.mod
  go.sum
Labels: enhancement

#96 Make git package public
  Dockerfile
  controllers/gitrepository_controller.go
  pkg/git/checkout.go
  pkg/git/transport.go
  pkg/git/transport_test.go
Labels: area/git, enhancement

#98 Helm: allow configuration of TLS certs without CA
  controllers/helmrepository_controller_test.go
  internal/helm/getter.go
  internal/helm/getter_test.go
Labels: area/helm, bug

#99 Remove local actions and use those from fluxcd/pkg
  .github/actions/kubebuilder/Dockerfile
  .github/actions/kubebuilder/action.yml
  .github/actions/kubebuilder/entrypoint.sh
  .github/actions/kustomize/Dockerfile
  .github/actions/kustomize/action.yml
  .github/actions/kustomize/entrypoint.sh
  .github/workflows/e2e.yaml
Labels: area/build

#100 Change CRD domain to 'source.toolkit.fluxcd.io'
  CHANGELOG.md
  PROJECT
  README.md
  api/v1alpha1/doc.go
  api/v1alpha1/groupversion_info.go
  config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml
  config/crd/bases/source.toolkit.fluxcd.io_helmcharts.yaml
  config/crd/bases/source.toolkit.fluxcd.io_helmrepositories.yaml
  config/crd/kustomization.yaml
  config/rbac/gitrepository_editor_role.yaml
  config/rbac/gitrepository_viewer_role.yaml
  config/rbac/helmchart_editor_role.yaml
  config/rbac/helmchart_viewer_role.yaml
  config/rbac/helmrepository_editor_role.yaml
  config/rbac/helmrepository_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/source_v1alpha1_gitrepository.yaml
  config/samples/source_v1alpha1_helmchart.yaml
  config/samples/source_v1alpha1_helmrepository.yaml
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
  docs/api/source.md
  docs/spec/v1alpha1/README.md
  docs/spec/v1alpha1/gitrepositories.md
  docs/spec/v1alpha1/helmcharts.md
  docs/spec/v1alpha1/helmrepositories.md
Labels: enhancement
