Repository fluxcd/source-controller, pull requests merged in 2020-09, with the labels that each got.

#125 Bugfix: `ArtifactExist` method and Helm chart packaging
  controllers/helmchart_controller.go
  controllers/storage.go
Labels: area/helm, bug

#130 Publish amd64/arm64 images to GHCR
  .github/workflows/release.yml
  Dockerfile
Labels: area/build

#129 doc/spec: update HelmChart examples
  docs/spec/v1alpha1/helmcharts.md
Labels: area/docs, area/helm

#134 Storage, garbage collection and artifact improvements
  api/v1alpha1/artifact.go
  api/v1alpha1/source.go
  config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml
  config/crd/bases/source.toolkit.fluxcd.io_helmcharts.yaml
  config/crd/bases/source.toolkit.fluxcd.io_helmrepositories.yaml
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
  controllers/storage.go
  controllers/storage_test.go
  docs/api/source.md
  docs/spec/v1alpha1/common.md
Labels: area/storage

#135 Configure manager logging and set level to info
  config/manager/deployment.yaml
  main.go
Labels: enhancement

#133 Improve storage write operations
  .github/workflows/release.yml
  api/v1alpha1/gitrepository_types.go
  api/v1alpha1/helmchart_types.go
  api/v1alpha1/helmrepository_types.go
  config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml
  config/crd/bases/source.toolkit.fluxcd.io_helmcharts.yaml
  config/crd/bases/source.toolkit.fluxcd.io_helmrepositories.yaml
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
  controllers/helmrepository_controller_test.go
  controllers/storage.go
  controllers/storage_test.go
  docs/api/source.md
  go.mod
  go.sum
  internal/fs/LICENSE
  internal/fs/fs.go
  internal/fs/fs_test.go
  internal/fs/rename.go
  internal/fs/rename_windows.go
  internal/fs/testdata/symlinks/dir-symlink
  internal/fs/testdata/symlinks/file-symlink
  internal/fs/testdata/symlinks/invalid-symlink
  internal/fs/testdata/symlinks/windows-file-symlink
  internal/fs/testdata/test.file
Labels: area/storage, enhancement

#139 Include PATCH rule for events in manager-role
  Makefile
  config/rbac/leader_election_role.yaml
  config/rbac/role.yaml
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
Labels: bug

#141 Conditionally remove artifact from source status
  Makefile
  api/v1alpha1/gitrepository_types.go
  api/v1alpha1/helmchart_types.go
  api/v1alpha1/helmrepository_types.go
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmchart_controller_test.go
  controllers/helmrepository_controller.go
Labels: area/storage, bug

#143 Add watch all namespaces flag
  config/manager/deployment.yaml
  main.go
Labels: enhancement

#147 Add Bucket type to source API spec
  docs/diagrams/source-controller-overview.png
  docs/spec/v1alpha1/README.md
  docs/spec/v1alpha1/buckets.md
Labels: area/docs

#148 ci: add sanity check for container images
  .github/workflows/release.yml
Labels: area/build

#146 Implement S3 bucket source
  .github/workflows/e2e.yaml
  PROJECT
  api/v1alpha1/bucket_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/source.toolkit.fluxcd.io_buckets.yaml
  config/crd/kustomization.yaml
  config/rbac/bucket_editor_role.yaml
  config/rbac/bucket_viewer_role.yaml
  config/rbac/role.yaml
  config/samples/source_v1alpha1_bucket.yaml
  config/testdata/minio/manifests/namespace/namespace.yaml
  config/testdata/minio/manifests/namespace/role.yaml
  config/testdata/minio/manifests/podinfo/deployment.yaml
  config/testdata/minio/manifests/podinfo/service.yaml
  config/testdata/minio/source.yaml
  controllers/bucket_controller.go
  controllers/gitrepository_controller.go
  controllers/storage.go
  controllers/storage_test.go
  docs/api/source.md
  go.mod
  go.sum
  main.go
Labels: enhancement

#152 Publish ARM v7/v8 multi-arch image to GHCR
  .github/workflows/release.yml
Labels: area/build

#153 Update Helm to v3.3.3
  go.mod
  go.sum
Labels: area/helm

#151 Support Helm charts from Bucket sources
  .github/workflows/e2e.yaml
  api/v1alpha1/helmchart_types.go
  config/crd/bases/source.toolkit.fluxcd.io_helmcharts.yaml
  config/testdata/bucket/source.yaml
  config/testdata/helmchart-from-bucket/source.yaml
  config/testdata/minio/secret.yaml
  controllers/helmchart_controller.go
  controllers/helmchart_controller_test.go
  docs/api/source.md
  docs/spec/v1alpha1/helmcharts.md
Labels: area/helm, enhancement

#154 Factor out duplicate snippets
  .github/workflows/e2e.yaml
  api/v1alpha1/artifact.go
  controllers/bucket_controller.go
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
  controllers/storage.go
  internal/helm/chart.go
  internal/helm/getter.go
Labels: enhancement

#155 Prevent resources getting stuck on transient err
  api/v1alpha1/artifact_types.go
  api/v1alpha1/condition_types.go
  api/v1alpha1/source.go
  controllers/bucket_controller.go
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmchart_controller_test.go
  controllers/helmrepository_controller.go
  controllers/helmrepository_controller_test.go
Labels: bug

#157 Factor out Helm repo index and chart download
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
  controllers/helmrepository_controller_test.go
  internal/helm/getter.go
  internal/helm/repository.go
  internal/helm/repository_test.go
  internal/helm/testdata/chartmuseum-index.yaml
  internal/helm/testdata/local-index-unordered.yaml
  internal/helm/testdata/local-index.yaml
Labels: area/helm, enhancement
