Repository fluxcd/source-controller, pull requests merged in 2020-11, with the labels that each got.

#201 Update engineerd/setup-kind to v0.5.0
  .github/workflows/e2e.yaml
Labels: area/build

#202 Patch status sub-resource
  .github/workflows/e2e.yaml
  controllers/bucket_controller.go
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
Labels: enhancement

#208 Prevent GC from wiping artifacts in the same NS
  controllers/bucket_controller.go
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
Labels: bug

#195 Refactor to adopt k8s standardized Condition type
  api/go.mod
  api/go.sum
  api/v1beta1/bucket_types.go
  api/v1beta1/gitrepository_types.go
  api/v1beta1/helmchart_types.go
  api/v1beta1/helmrepository_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/source.toolkit.fluxcd.io_buckets.yaml
  config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml
  config/crd/bases/source.toolkit.fluxcd.io_helmcharts.yaml
  config/crd/bases/source.toolkit.fluxcd.io_helmrepositories.yaml
  controllers/bucket_controller.go
  controllers/gitrepository_controller.go
  controllers/gitrepository_controller_test.go
  controllers/helmchart_controller.go
  controllers/helmchart_controller_test.go
  controllers/helmrepository_controller.go
  docs/api/source.md
  go.mod
  go.sum
  hack/api-docs/config.json
Labels: enhancement

#215 Implement source suspension
  api/v1beta1/bucket_types.go
  api/v1beta1/gitrepository_types.go
  api/v1beta1/helmchart_types.go
  api/v1beta1/helmrepository_types.go
  config/crd/bases/source.toolkit.fluxcd.io_buckets.yaml
  config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml
  config/crd/bases/source.toolkit.fluxcd.io_helmcharts.yaml
  config/crd/bases/source.toolkit.fluxcd.io_helmrepositories.yaml
  controllers/bucket_controller.go
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
  docs/api/source.md
  docs/spec/v1beta1/buckets.md
  docs/spec/v1beta1/common.md
  docs/spec/v1beta1/gitrepositories.md
  docs/spec/v1beta1/helmcharts.md
  docs/spec/v1beta1/helmrepositories.md
Labels: enhancement

#220 List HelmChart for GitRepository change
  controllers/helmchart_controller.go
Labels: bug

#223 Respect configured user in SSH Git repository URL
  controllers/gitrepository_controller.go
  pkg/git/transport.go
  pkg/git/transport_test.go
Labels: area/git, bug
