Repository fluxcd/source-controller, pull requests merged in 2021-02, with the labels that each got.

#273 Only start file server for elected leader
  config/manager/deployment.yaml
  main.go
Labels: enhancement

#280 Properly escape outer loop for present dependency
  controllers/helmchart_controller.go
Labels: area/helm, bug

#282 Enable pprof endpoints on metrics server
  go.mod
  go.sum
  main.go
Labels: area/build

#285 Add fsGroup to pod security context
  Dockerfile
  config/manager/deployment.yaml
Labels: area/build

#286 Fix chart with custom valuesFile (0bytes tgz)
  controllers/helmchart_controller.go
Labels: area/helm, bug

#289 Use musl and libgit2 packages from v3.13 branch
  Dockerfile
Labels: area/build

#288 libgit2: use provided host to validate public key
  pkg/git/libgit2/transport.go
  pkg/git/libgit2/transport_test.go
Labels: area/git, bug

#290 libgit2: check hostkey type when validating hostkey
  pkg/git/libgit2/transport.go
  pkg/git/libgit2/transport_test.go
Labels: area/git, bug

#294 Copy loop iterator var for use by goroutine
  internal/helm/dependency_manager.go
Labels: area/helm, bug

#298 Typo fix in GitRepositories doc file
  docs/spec/v1beta1/gitrepositories.md
Labels: area/docs

#299 Update dependencies
  Makefile
  api/go.mod
  api/go.sum
  config/crd/bases/source.toolkit.fluxcd.io_buckets.yaml
  config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml
  config/crd/bases/source.toolkit.fluxcd.io_helmcharts.yaml
  config/crd/bases/source.toolkit.fluxcd.io_helmrepositories.yaml
  go.mod
  go.sum
  internal/helm/repository_test.go
Labels: area/build

#300 Refactor release workflow
  .github/workflows/release.yml
Labels: area/build

#302 Fix release workflow
  .github/workflows/release.yml
Labels: area/build
