Repository fluxcd/source-controller, pull requests merged in 2021-12, with the labels that each got.

#507 controllers: use short SHA in chart SemVer meta
  controllers/helmchart_controller.go
  controllers/helmchart_controller_test.go
Labels: bug, area/helm

#514 Change bucket JSONPath from URL to endpoint
  api/v1beta1/bucket_types.go
  config/crd/bases/source.toolkit.fluxcd.io_buckets.yaml
Labels: area/bucket

#520 Update build dependencies
  .github/actions/run-tests/Dockerfile
  Dockerfile
Labels: area/build

#515 Fix potentially broken support for macOS
  Makefile
Labels: area/build

#505 docs: extend development documentation
  DEVELOPMENT.md
Labels: area/docs
