Repository fluxcd/source-controller, pull requests merged in 2021-11, with the labels that each got.

#489 tests: ensure proper garbage collection
  controllers/helmchart_controller_test.go
  controllers/helmrepository_controller_test.go
  pkg/git/libgit2/checkout_test.go
Labels: area/build

#493 Update various dependencies to mitigate CVE warnings
  go.mod
  go.sum
Labels: area/build

#485 helm: factor out logic from controller into package
  controllers/helmchart_controller.go
  controllers/helmchart_controller_test.go
  controllers/helmrepository_controller.go
  go.mod
  go.sum
  internal/helm/chart.go
  internal/helm/chart/builder.go
  internal/helm/chart/builder_local.go
  internal/helm/chart/builder_local_test.go
  internal/helm/chart/builder_remote.go
  internal/helm/chart/builder_remote_test.go
  internal/helm/chart/builder_test.go
  internal/helm/chart/dependency_manager.go
  internal/helm/chart/dependency_manager_test.go
  internal/helm/chart/errors.go
  internal/helm/chart/errors_test.go
  internal/helm/chart/metadata.go
  internal/helm/chart/metadata_test.go
  internal/helm/chart_test.go
  internal/helm/dependency_manager.go
  internal/helm/dependency_manager_test.go
  internal/helm/getter/getter.go
  internal/helm/getter/getter_test.go
  internal/helm/helm.go
  internal/helm/repository.go
  internal/helm/repository/chart_repository.go
  internal/helm/repository/chart_repository_test.go
  internal/helm/repository/utils.go
  internal/helm/repository/utils_test.go
  internal/helm/repository_test.go
  internal/helm/testdata/charts/empty.tgz
  internal/helm/testdata/charts/helmchart-0.1.0.tgz
  internal/helm/testdata/charts/helmchart-v1/.helmignore
  internal/helm/testdata/charts/helmchart-v1/Chart.yaml
  internal/helm/testdata/charts/helmchart-v1/templates/NOTES.txt
  internal/helm/testdata/charts/helmchart-v1/templates/_helpers.tpl
  internal/helm/testdata/charts/helmchart-v1/templates/deployment.yaml
  internal/helm/testdata/charts/helmchart-v1/templates/ingress.yaml
  internal/helm/testdata/charts/helmchart-v1/templates/service.yaml
  internal/helm/testdata/charts/helmchart-v1/templates/serviceaccount.yaml
  internal/helm/testdata/charts/helmchart-v1/templates/tests/test-connection.yaml
  internal/helm/testdata/charts/helmchart-v1/values.yaml
  internal/helm/testdata/charts/helmchart/values-prod.yaml
  internal/helm/testdata/charts/helmchartwithdeps-v1-0.3.0.tgz
  internal/helm/testdata/charts/helmchartwithdeps-v1/.helmignore
  internal/helm/testdata/charts/helmchartwithdeps-v1/Chart.yaml
  internal/helm/testdata/charts/helmchartwithdeps-v1/requirements.yaml
  internal/helm/testdata/charts/helmchartwithdeps-v1/templates/NOTES.txt
  internal/helm/testdata/charts/helmchartwithdeps-v1/templates/_helpers.tpl
  internal/helm/testdata/charts/helmchartwithdeps-v1/templates/deployment.yaml
  internal/helm/testdata/charts/helmchartwithdeps-v1/templates/ingress.yaml
  internal/helm/testdata/charts/helmchartwithdeps-v1/templates/service.yaml
  internal/helm/testdata/charts/helmchartwithdeps-v1/templates/serviceaccount.yaml
  internal/helm/testdata/charts/helmchartwithdeps-v1/templates/tests/test-connection.yaml
  internal/helm/testdata/charts/helmchartwithdeps-v1/values.yaml
  internal/helm/testdata/charts/helmchartwithdeps/Chart.lock
  main.go
Labels: enhancement, area/helm

#496 Update test shield link
  README.md
Labels: area/docs

#497 Update controller-runtime to v0.10.2
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#498 Update github.com/minio/minio-go to `v7.0.15`
  go.mod
  go.sum
  pkg/gcp/gcp_test.go
Labels: area/build

#500 controllers: absolute local path for cached chart
  controllers/helmchart_controller.go
Labels: bug, area/helm

#502 internal/helm: LoadChartMetadataFromArchive improvements
  internal/helm/chart/metadata.go
Labels: area/helm

#503 internal/helm: validate loaded chart metadata obj
  internal/helm/chart/builder_local.go
  internal/helm/chart/builder_remote.go
Labels: area/helm
