Repository fluxcd/source-controller, pull requests merged in 2021-06, with the labels that each got.

#370 Update go-git to v5.4.2
  .github/workflows/e2e.yaml
  config/testdata/git/large-repo.yaml
  go.mod
  go.sum
Labels: area/build

#372 Reinstate Git cloning timeout
  controllers/gitrepository_controller.go
Labels: area/git

#376 Add nightly builds workflow
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: area/build

#378 Use `github.repository` property for image name
  .github/workflows/nightly.yml
Labels: area/build

#377 Use `binutils-gold` in builder image
  Dockerfile
Labels: area/build

#382 Unpin docker Go Module dependency
  go.mod
  go.sum
Labels: area/build

#386 Use Debian instead of Alpine for multi-arch builds
  Dockerfile
Labels: area/build, enhancement

#388 Update Helm to v3.6.1
  api/v1beta1/helmrepository_types.go
  config/crd/bases/source.toolkit.fluxcd.io_helmrepositories.yaml
  controllers/helmchart_controller.go
  controllers/helmchart_controller_test.go
  controllers/helmrepository_controller.go
  docs/api/source.md
  docs/spec/v1beta1/helmrepositories.md
  go.mod
  go.sum
Labels: area/build, area/helm

#391 Use libgit2 from "unstable" / "sid"
  .github/actions/run-tests/Dockerfile
  Dockerfile
  config/testdata/git/large-repo.yaml
Labels: area/build, area/git

#394 Fix tag checkout with libgit2
  pkg/git/libgit2/checkout.go
  pkg/git/libgit2/checkout_test.go
Labels: area/git, bug

#396 Print pods status on e2e failures
  .github/workflows/e2e.yaml
Labels: area/build
