Repository fluxcd/source-controller, pull requests merged in 2021-01, with the labels that each got.

#246 Upgrade controller-runtime to v0.7.0
  api/go.mod
  api/go.sum
  api/v1beta1/gitrepository_types.go
  api/v1beta1/source.go
  config/manager/deployment.yaml
  config/rbac/leader_election_role.yaml
  controllers/bucket_controller.go
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
  controllers/helmrepository_controller_test.go
  controllers/source_predicate.go
  controllers/suite_test.go
  go.mod
  go.sum
  internal/util/util.go
  main.go
Labels: area/build, hold

#252 Publish as single multi-arch Docker image
  .github/workflows/release.yml
Labels: area/build

#255 Upgrade runtime package to v0.6.2
  controllers/bucket_controller.go
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
  go.mod
  go.sum
Labels: area/build

#258 Update Kubernetes and Helm packages
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#260 Align HelmChart source indexer and watches
  api/v1beta1/source.go
  controllers/helmchart_controller.go
Labels: bug

#261 Fix unreachable code issue in helmchart reconciler
  controllers/helmchart_controller.go
Labels: bug

#264 Fix values file override
  controllers/helmchart_controller.go
Labels: area/helm, bug

#265 Update fluxcd/pkg/runtime to v0.8.0
  api/go.mod
  api/go.sum
  api/v1beta1/bucket_types.go
  api/v1beta1/gitrepository_types.go
  api/v1beta1/helmrepository_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/source.toolkit.fluxcd.io_buckets.yaml
  config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml
  config/crd/bases/source.toolkit.fluxcd.io_helmrepositories.yaml
  controllers/helmchart_controller_test.go
  controllers/helmrepository_controller_test.go
  docs/api/source.md
  go.mod
  go.sum
  main.go
Labels: area/build

#267 Rely on index checksum for HelmRepository reconcile operation
  controllers/helmrepository_controller.go
Labels: area/helm, enhancement

#269 Assume local dependency without Helm repository
  controllers/helmchart_controller.go
  internal/helm/dependency_manager.go
Labels: area/helm, bug
