Repository fluxcd/source-controller, pull requests merged in 2021-04, with the labels that each got.

#337 Check ignore matches before Bucket item downloads
  .github/actions/run-tests/Dockerfile
  Dockerfile
  api/go.mod
  controllers/bucket_controller.go
  controllers/gitrepository_controller.go
  controllers/storage.go
  controllers/storage_test.go
  go.mod
  pkg/sourceignore/sourceignore.go
  pkg/sourceignore/sourceignore_test.go
Labels: area/bucket, area/git, area/storage, enhancement

#340 Update Helm to v3.5.4
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#342 Update fluxcd/pkg/runtime to v0.10.2
  go.mod
  go.sum
Labels: area/build

#305 Add `ValuesFiles` to HelmChart spec
  api/v1beta1/helmchart_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/source.toolkit.fluxcd.io_helmcharts.yaml
  config/testdata/helmchart-valuesfile/helmchart_gitrepository.yaml
  config/testdata/helmchart-valuesfile/helmchart_helmrepository.yaml
  controllers/helmchart_controller.go
  controllers/helmchart_controller_test.go
  docs/api/source.md
  docs/spec/v1beta1/helmcharts.md
Labels: area/helm, enhancement

#344 Update fluxcd/pkg/runtime to v0.11.0
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#345 Write chart data on identitical values overwrite
  controllers/helmchart_controller.go
  controllers/helmchart_controller_test.go
  controllers/testdata/charts/helmchart/duplicate.yaml
Labels: area/helm, bug

#351 Configure ignore domain for GitRepository rules
  controllers/gitrepository_controller.go
Labels: bug
