Repository fluxcd/source-controller, pull requests merged in 2022-11, with the labels that each got.

#931 Upgrade to `azure-sdk-for-go/storage/azblob` v0.5.1
  go.mod
  go.sum
  pkg/azure/blob.go
  pkg/azure/blob_integration_test.go
  pkg/azure/blob_test.go
Labels: area/bucket

#950 Update dependencies
  controllers/ocirepository_controller.go
  go.mod
  go.sum
Labels: area/build

#945 gogit: Add new ForceGoGitImplementation FeatureGate
  controllers/gitrepository_controller.go
  controllers/gitrepository_controller_test.go
  controllers/suite_test.go
  docs/spec/v1beta2/gitrepositories.md
  internal/features/features.go
  main.go
Labels: area/git

#958 Remove nsswitch.conf creation
  Dockerfile
Labels: area/build

#959 gitrepo: bump git packages
  controllers/gitrepository_controller.go
  go.mod
  go.sum
Labels: area/build

#960 Update dependencies
  api/go.mod
  api/go.sum
  controllers/gitrepository_controller_test.go
  controllers/storage.go
  controllers/storage_test.go
  go.mod
  go.sum
  tests/fuzz/gitrepository_fuzzer.go
Labels: area/build

#965 Migrate to Go Native fuzz and improve reliability
  ATTRIBUTIONS.md
  Makefile
  controllers/gitrepository_controller_fuzz_test.go
  tests/fuzz/Dockerfile.builder
  tests/fuzz/README.md
  tests/fuzz/compile_native_go_fuzzer
  tests/fuzz/go.mod
  tests/fuzz/native_go_run.sh
  tests/fuzz/oss_fuzz_build.sh
  tests/fuzz/oss_fuzz_prebuild.sh
Labels: area/build

#968 build: Add postbuild script for fuzzing
  tests/fuzz/oss_fuzz_postbuild.sh
Labels: area/build

#969 build: Link libgit2 via LIB_FUZZING_ENGINE
  tests/fuzz/oss_fuzz_postbuild.sh
  tests/fuzz/oss_fuzz_prebuild.sh
Labels: area/build
