Repository fluxcd/source-controller, pull requests merged in 2022-01, with the labels that each got.

#529 Update containerd to v1.5.8 (fix GHSA-5j5w-g665-5m35)
  go.mod
  go.sum
Labels: area/build

#532 Update containerd to v1.5.9 (fix CVE-2021-43816)
  go.mod
  go.sum
Labels: area/build

#533 Log the error when tmp cleanup fails
  api/v1beta1/zz_generated.deepcopy.go
  controllers/bucket_controller.go
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
Labels: area/storage

#538 Update file close operation to not use defer and add test case for CopyFromPath
  controllers/storage.go
  controllers/storage_test.go
Labels: area/storage

#540 helm: remove temp file name from index cache err
  internal/helm/repository/chart_repository.go
Labels: bug, area/helm

#523 Statically build source-controller
  .github/actions/run-tests/Dockerfile
  .github/workflows/e2e.yaml
  .gitignore
  ATTRIBUTIONS.md
  Dockerfile
  Makefile
  docs/api/source.md
  hack/ci/e2e.sh
  hack/update-attributions.sh
Labels: enhancement, area/build

#539 Fix makefile envtest and controller-gen usage
  .github/workflows/e2e.yaml
  .gitignore
  Makefile
  controllers/suite_test.go
Labels: area/build

#542 Use patch instead of update when adding finalizers
  controllers/bucket_controller.go
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
Labels: enhancement

#545 git/libgit2: fix failing tests when the default branch is not "master"
  pkg/git/libgit2/checkout_test.go
Labels: area/git

#524 libgit2: Configured libgit2 clone ProxyOptions
  go.mod
  go.sum
  pkg/git/libgit2/checkout.go
  pkg/git/strategy/proxy/strategy_proxy_test.go
Labels: enhancement, area/git

#549 e2e: Set timeout to fix intermittent errors
  config/testdata/git/large-repo.yaml
  hack/ci/e2e.sh
Labels: area/build

#547 docs: Add git proxy support docs
  docs/spec/v1beta1/gitrepositories.md
Labels: area/docs

#550 Publish SBOM and sign release artifacts
  .github/workflows/release.yml
  .goreleaser.yaml
  Dockerfile
Labels: enhancement, area/build

#543 storage: include directories in artifact tarball
  controllers/storage.go
  controllers/storage_test.go
Labels: enhancement, area/storage

#551 Add Permissions to github Workflows
  .github/workflows/e2e.yaml
  .github/workflows/nightly.yml
  .github/workflows/scan.yaml
Labels: area/build

#554 Update git2go to v31.7.6
  go.mod
  go.sum
Labels: area/git

#555 Update dev docs
  DEVELOPMENT.md
Labels: area/docs

#558 Statically build using musl toolchain and target alpine
  Dockerfile
  Makefile
Labels: enhancement, area/build

#560 Pin target image to alpine:3.15
  Dockerfile
Labels: area/build
