Repository fluxcd/source-controller, pull requests merged in 2022-04, with the labels that each got.

#651 update toolkit.fluxcd.io docs links
  CHANGELOG.md
  README.md
Labels: area/docs

#655 Add flag to allow configuration of SSH kex algos
  main.go
  pkg/git/gogit/transport.go
  pkg/git/gogit/transport_test.go
  pkg/git/libgit2/managed/ssh.go
  pkg/git/options.go
Labels: enhancement, area/git

#638 Garbage collect with provided retention options
  controllers/bucket_controller.go
  controllers/bucket_controller_test.go
  controllers/gitrepository_controller.go
  controllers/gitrepository_controller_test.go
  controllers/helmchart_controller.go
  controllers/helmchart_controller_test.go
  controllers/helmrepository_controller.go
  controllers/helmrepository_controller_test.go
  controllers/storage.go
  controllers/storage_test.go
  controllers/suite_test.go
  main.go
  tests/fuzz/gitrepository_fuzzer.go
Labels: enhancement, area/storage

#624 Add notify() in all the reconcilers
  controllers/bucket_controller.go
  controllers/bucket_controller_test.go
  controllers/gitrepository_controller.go
  controllers/gitrepository_controller_test.go
  controllers/helmchart_controller.go
  controllers/helmchart_controller_test.go
  controllers/helmrepository_controller.go
  controllers/helmrepository_controller_test.go
  internal/reconcile/reconcile.go
  internal/reconcile/reconcile_test.go
Labels: enhancement

#658 libgit2: managed transport improvements
  pkg/git/libgit2/managed/const.go
  pkg/git/libgit2/managed/http.go
  pkg/git/libgit2/managed/ssh.go
Labels: area/git

#663 helm: introduce customized chart loaders
  controllers/helmchart_controller.go
  internal/helm/chart/builder.go
  internal/helm/chart/builder_local.go
  internal/helm/chart/builder_local_test.go
  internal/helm/chart/builder_remote.go
  internal/helm/chart/builder_remote_test.go
  internal/helm/chart/builder_test.go
  internal/helm/chart/dependency_manager.go
  internal/helm/chart/dependency_manager_test.go
  internal/helm/chart/secureloader/directory.go
  internal/helm/chart/secureloader/directory_test.go
  internal/helm/chart/secureloader/file.go
  internal/helm/chart/secureloader/ignore/doc.go
  internal/helm/chart/secureloader/ignore/rules.go
  internal/helm/chart/secureloader/ignore/rules_test.go
  internal/helm/chart/secureloader/ignore/testdata/.helmignore
  internal/helm/chart/secureloader/ignore/testdata/.joonix
  internal/helm/chart/secureloader/ignore/testdata/a.txt
  internal/helm/chart/secureloader/ignore/testdata/cargo/a.txt
  internal/helm/chart/secureloader/ignore/testdata/cargo/b.txt
  internal/helm/chart/secureloader/ignore/testdata/cargo/c.txt
  internal/helm/chart/secureloader/ignore/testdata/helm.txt
  internal/helm/chart/secureloader/ignore/testdata/mast/a.txt
  internal/helm/chart/secureloader/ignore/testdata/mast/b.txt
  internal/helm/chart/secureloader/ignore/testdata/mast/c.txt
  internal/helm/chart/secureloader/ignore/testdata/rudder.txt
  internal/helm/chart/secureloader/ignore/testdata/templates/.dotfile
  internal/helm/chart/secureloader/ignore/testdata/tiller.txt
  internal/helm/chart/secureloader/loader.go
  internal/helm/chart/secureloader/loader_test.go
  internal/helm/chart/secureloader/sympath/walk.go
  internal/helm/chart/secureloader/sympath/walk_test.go
Labels: enhancement, area/helm

#664 Add flags to configure exponential back-off retry
  controllers/bucket_controller.go
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
  go.mod
  go.sum
  main.go
Labels: enhancement

#653 Change all file permissions to octal format
  controllers/bucket_controller_test.go
  controllers/gitrepository_controller_test.go
  controllers/helmchart_controller.go
  controllers/helmchart_controller_test.go
  controllers/helmrepository_controller_test.go
  controllers/storage.go
  controllers/storage_test.go
  internal/fs/fs_test.go
  internal/helm/chart/builder_local_test.go
  internal/helm/chart/metadata_test.go
  internal/helm/chart/secureloader/directory_test.go
  internal/helm/chart/secureloader/loader_test.go
  internal/helm/repository/chart_repository_test.go
  main.go
  pkg/gcp/gcp.go
  pkg/sourceignore/sourceignore_test.go
  tests/fuzz/gitrepository_fuzzer.go
Labels: enhancement

#674 Fix Kustomize installation broken link
  DEVELOPMENT.md
Labels: area/docs

#675 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#676 Update other dependencies
  controllers/bucket_controller_test.go
  controllers/gitrepository_controller_test.go
  controllers/helmchart_controller_test.go
  controllers/helmrepository_controller_test.go
  go.mod
  go.sum
  internal/reconcile/summarize/summary_test.go
  pkg/gcp/gcp_test.go
Labels: area/build

#667 HelmChart: enable dependency manager to use the in memory cache
  controllers/helmchart_controller.go
  controllers/suite_test.go
  go.mod
  internal/cache/metrics.go
  internal/helm/chart/builder_remote.go
  internal/helm/chart/dependency_manager.go
  internal/helm/repository/chart_repository.go
  main.go
Labels: enhancement, area/helm

#677 Update github.com/elazarl/goproxy
  go.mod
  go.sum
Labels: area/build

#683 fix panic when HelmRepository's artifact size is nil
  controllers/helmrepository_controller.go
  controllers/helmrepository_controller_test.go
Labels: bug, area/helm

#686 tests: Fix flakiness of git related tests
  Makefile
  controllers/gitrepository_controller_test.go
  controllers/helmrepository_controller_test.go
Labels: area/build

#685 helm: optimise repository index loading
  api/v1beta2/artifact_types.go
  controllers/helmrepository_controller.go
  internal/helm/repository/chart_repository.go
Labels: enhancement, area/helm

#691 helmrepo: same revision different checksum scenario
  controllers/helmrepository_controller.go
  controllers/helmrepository_controller_test.go
Labels: enhancement, area/helm

#692 build: let users pass test flags to `make test`
  DEVELOPMENT.md
  Makefile
Labels: area/build

#701 test: use `T.TempDir` to create temporary test directory
  controllers/bucket_controller_fetch_test.go
  controllers/bucket_controller_test.go
  controllers/gitrepository_controller_test.go
  controllers/helmchart_controller_test.go
  controllers/helmrepository_controller_test.go
  controllers/storage_test.go
  internal/fs/fs_test.go
  internal/helm/chart/builder_local_test.go
  internal/helm/chart/builder_remote_test.go
  internal/helm/chart/metadata_test.go
  internal/helm/repository/chart_repository_test.go
  pkg/gcp/gcp_test.go
  pkg/git/gogit/checkout_test.go
  pkg/git/libgit2/checkout_test.go
  pkg/git/libgit2/managed/managed_test.go
  pkg/git/strategy/proxy/strategy_proxy_test.go
  pkg/git/strategy/strategy_test.go
  pkg/minio/minio_test.go
  pkg/sourceignore/sourceignore_test.go
Labels: area/testing

#702 Switch to gen-crd-api-reference-docs from master
  Makefile
  docs/api/source.md
Labels: area/docs, area/build

#699 docs: Remove all traces of "identity.pub" from docs
  api/v1beta2/gitrepository_types.go
  config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml
  docs/api/source.md
  docs/spec/v1beta2/gitrepositories.md
Labels: area/docs, area/git
