Repository fluxcd/source-controller, pull requests merged in 2022-12, with the labels that each got.

#981 minio: use container image for tests
  .github/workflows/tests.yaml
  go.mod
  go.sum
  pkg/minio/minio_test.go
Labels: area/build, area/bucket

#982 helm: Update SDK to v3.10.3
  go.mod
  go.sum
Labels: area/helm, area/build

#985 Update dependencies
  go.mod
  go.sum
Labels: area/build

#988 Fix aliased chart dependencies resolution
  controllers/helmchart_controller_test.go
  internal/helm/chart/dependency_manager.go
Labels: bug, area/helm

#991 storage: take lock files into consideration while garbage collecting
  controllers/storage.go
  main.go
Labels: bug, area/storage
