Repository fluxcd/source-controller, pull requests merged in 2023-01, with the labels that each got.

#998 Fix OCIRepository testdata permissions
  controllers/ocirepository_controller_test.go
Labels: area/testing

#1008 Update dependencies
  api/go.mod
  api/go.sum
  controllers/bucket_controller.go
  controllers/gitrepository_controller.go
  controllers/helmchart_controller.go
  controllers/helmrepository_controller.go
  controllers/helmrepository_controller_oci.go
  controllers/ocirepository_controller.go
  controllers/ocirepository_controller_test.go
  go.mod
  go.sum
Labels: dependencies

#1009 build: Enable SBOM and SLSA Provenance
  .github/workflows/release.yml
  Dockerfile
Labels: area/build

#1010 CI: Replace engineerd/setup-kind with helm/kind-action
  .github/workflows/e2e.yaml
  .github/workflows/release.yml
Labels: area/build
