Repository fluxcd/source-controller, pull requests merged in 2023-12, with the labels that each got.

#1304 Update Go dependencies
  go.mod
  go.sum
Labels: dependencies

#1308 Update dependencies
  go.mod
  go.sum
Labels: dependencies, backport:release/v1.2.x

#1317 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/oci, dependencies, backport:release/v1.2.x

#1320 Update fluxcd/pkg dependencies
  go.mod
  go.sum
Labels: dependencies, backport:release/v1.2.x
