Repository fluxcd/source-controller, pull requests merged in 2023-06, with the labels that each got.

#1126 Re-instantiate non-optimized clone fallback
  internal/controller/gitrepository_controller.go
  internal/controller/gitrepository_controller_test.go
Labels: area/git

#1125 Add SLSA3 generators to release workflow
  .github/workflows/release.yml
  .goreleaser.yaml
Labels: area/build

#1127 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies

#1132 Update Cosign to v2.1.0
  go.mod
  go.sum
  internal/controller/helmchart_controller_test.go
  internal/controller/ocirepository_controller_test.go
Labels: dependencies

#1134 Align `go.mod` version with Kubernetes (Go 1.20)
  api/go.mod
  go.mod
  tests/fuzz/Dockerfile.builder
Labels: area/build

#1136 Add the verification key to the GitRepository verified status condition
  internal/controller/gitrepository_controller.go
  internal/controller/gitrepository_controller_test.go
Labels: area/git

#1138 Add backport GitHub Action workflow
  .github/dependabot.yaml
  .github/labels.yaml
  .github/workflows/backport.yaml
  .github/workflows/cifuzz.yaml
  .github/workflows/scan.yaml
  .github/workflows/sync-labels.yaml
Labels: enhancement, area/build

#1141 Use standard labels from `fluxcd/community`
  .github/labels.yaml
  .github/workflows/sync-labels.yaml
Labels: area/ci

#1142 Rename backport job to align with other workflows
  .github/workflows/backport.yaml
Labels: area/ci
