Repository fluxcd/source-controller, pull requests merged in 2023-03, with the labels that each got.

#1040 Update Go to 1.20
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/scan.yaml
  .github/workflows/tests.yaml
  .github/workflows/verify.yaml
  Dockerfile
  Makefile
  internal/helm/repository/oci_chart_repository_test.go
Labels: area/build

#1036 Advertise absolute reference in Artifact for GitRepository name ref
  controllers/gitrepository_controller.go
  controllers/gitrepository_controller_test.go
  go.mod
  go.sum
Labels: enhancement, area/git

#1041 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#1044 Use `logger.SetLogger` to also configure `klog`
  go.mod
  go.sum
  main.go
Labels: enhancement

#1043 Update dependencies
  go.mod
  go.sum
Labels: area/build

#1045 build: update release workflow
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: area/build

#1047 release: pass `--yes` to cosign in signs
  .goreleaser.yaml
Labels: area/build

#1054 Update workflows
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/scan.yaml
  .github/workflows/tests.yaml
  .github/workflows/verify.yaml
Labels: area/build

#1059 Add reconciler sharding capability based on label selector
  Makefile
  go.mod
  go.sum
  main.go
Labels: enhancement

#1062 Update dependenies
  .github/dependabot.yaml
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/scan.yaml
  .github/workflows/tests.yaml
  .github/workflows/verify.yaml
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: area/build

#1048 Support Azure Workload Identity
  docs/spec/v1beta2/buckets.md
  docs/spec/v1beta2/helmrepositories.md
  docs/spec/v1beta2/ocirepositories.md
  go.mod
  go.sum
  pkg/azure/blob.go
  pkg/azure/blob_integration_test.go
Labels: enhancement, area/helm, area/bucket, area/oci

#1063 Add API docs links to readme
  README.md
  docs/spec/v1/README.md
  docs/spec/v1/gitrepositories.md
  docs/spec/v1beta2/helmrepositories.md
Labels: area/docs

#1064 ci: Remove the macOS runner
  .github/workflows/tests.yaml
Labels: area/build
