Repository fluxcd/source-controller, pull requests merged in 2023-07, with the labels that each got.

#1144 gitrepo: remove obsolete proxy docs
  docs/spec/v1/gitrepositories.md
Labels: area/docs

#1145 Update go-git to unreleased v5.8.0
  go.mod
  go.sum
  internal/controller/gitrepository_controller_test.go
Labels: area/git, dependencies

#1146 ci: update kind to v0.19.0
  .github/workflows/e2e.yaml
Labels: area/ci, dependencies

#1147 Update Go dependencies
  go.mod
  go.sum
  pkg/gcp/gcp_test.go
Labels: dependencies

#1149 ci: various workflow changes
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/release.yml
  .github/workflows/scan.yaml
  .github/workflows/tests.yaml
  .github/workflows/verify.yaml
Labels: area/ci

#1151 ci: use bot token for backport
  .github/workflows/backport.yaml
Labels: area/ci

#1152 ci: group Dependabot GitHub Action updates
  .github/dependabot.yaml
Labels: area/ci, dependencies

#1156 Fix GHA backport.yaml workflow job perms
  .github/workflows/backport.yaml
  .github/workflows/release.yml
Labels: area/ci, backport:release/v1.0.x

#1158 Update `fluxcd/pkg/oci` to fix ECR cross-region auth
  go.mod
  go.sum
Labels: area/oci, dependencies, backport:release/v1.0.x

#1170 Fix the helm cache arguments
  main.go
Labels: area/helm, backport:release/v1.0.x

#1109 gitrepo: Add support for specifying proxy per `GitRepository`
  Makefile
  api/v1/gitrepository_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml
  docs/api/v1/source.md
  docs/spec/v1/gitrepositories.md
  internal/controller/gitrepository_controller.go
  internal/controller/gitrepository_controller_test.go
Labels: enhancement, area/git

#1179 Unpin go-git and update to v5.8.1
  go.mod
  go.sum
Labels: dependencies, backport:release/v1.0.x

#1160 helmrepo: add `.spec.certSecretRef` for specifying TLS auth data
  api/v1beta2/helmrepository_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/source.toolkit.fluxcd.io_helmrepositories.yaml
  docs/api/v1beta2/source.md
  docs/spec/v1beta2/helmrepositories.md
  internal/controller/helmchart_controller.go
  internal/controller/helmchart_controller_test.go
  internal/controller/helmrepository_controller.go
  internal/controller/helmrepository_controller_oci.go
  internal/controller/helmrepository_controller_test.go
  internal/controller/ocirepository_controller.go
  internal/helm/getter/client_opts.go
  internal/helm/getter/client_opts_test.go
  internal/helm/getter/getter.go
  internal/helm/getter/getter_test.go
  internal/helm/registry/auth.go
  internal/oci/auth.go
Labels: enhancement, area/helm, area/api

#1176 ocirepo: add cosign support for insecure HTTP registries
  go.mod
  go.sum
  internal/controller/helmchart_controller_test.go
  internal/controller/helmrepository_controller_oci_test.go
  internal/controller/ocirepository_controller.go
  internal/controller/ocirepository_controller_test.go
  internal/controller/suite_test.go
  internal/controller/testdata/certs/Makefile
  internal/controller/testdata/certs/client-csr.json
  internal/controller/testdata/certs/client-key.pem
  internal/controller/testdata/certs/client.csr
  internal/controller/testdata/certs/client.pem
Labels: area/oci
