Repository fluxcd/source-controller, pull requests merged in 2024-04, with the labels that each got.

#1425 Update dependencies to Go 1.22 and Kubernetes 1.29.3
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/scan.yaml
  .github/workflows/tests.yaml
  .github/workflows/verify.yaml
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  tests/fuzz/Dockerfile.builder
Labels: dependencies

#1427 Generate unique names for notation secrets
  internal/controller/ocirepository_controller_test.go
Labels: area/testing

#1430 Sanitize URLs for bucket fetch error messages
  internal/controller/bucket_controller.go
  internal/error/sanitized.go
  internal/error/sanitized_test.go
Labels: area/bucket, backport:release/v1.2.x

#1442 Update dependencies to cosign v2.2.4
  go.mod
  go.sum
  internal/controller/helmchart_controller_test.go
  internal/controller/ocirepository_controller_test.go
  pkg/gcp/gcp_test.go
Labels: dependencies

#1412 Helm: Allow insecure registry login
  .github/workflows/tests.yaml
  internal/controller/suite_test.go
  internal/helm/getter/client_opts.go
  internal/helm/getter/client_opts_test.go
Labels: area/helm

#1457 Bind cached helm index to the maximum index size
  internal/helm/repository/chart_repository.go
  internal/helm/repository/chart_repository_test.go
Labels: bug, area/helm, area/storage

#1450 Update dependencies to Kubernetes 1.30
  .github/workflows/e2e.yaml
  .github/workflows/tests.yaml
  .github/workflows/verify.yaml
  Makefile
  api/go.mod
  api/go.sum
  config/crd/bases/source.toolkit.fluxcd.io_buckets.yaml
  config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml
  config/crd/bases/source.toolkit.fluxcd.io_helmcharts.yaml
  config/crd/bases/source.toolkit.fluxcd.io_helmrepositories.yaml
  config/crd/bases/source.toolkit.fluxcd.io_ocirepositories.yaml
  go.mod
  go.sum
Labels: dependencies
