Repository fluxcd/source-controller, pull requests merged in 2025-05, with the labels that each got.

#1790 [RFC-0010] Introduce object-level workload identity for OCIRepository
  config/rbac/role.yaml
  go.mod
  go.sum
  internal/controller/gitrepository_controller.go
  internal/controller/helmchart_controller.go
  internal/controller/ocirepository_controller.go
  internal/controller/ocirepository_controller_test.go
  internal/helm/getter/client_opts.go
  internal/oci/auth.go
  main.go
Labels: area/oci

#1806 Update dependencies
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies

#1810 Update dependencies
  go.mod
  go.sum
Labels: dependencies

#1812 Update containerd v1.7.27
  go.mod
  go.sum
  internal/controller/ocirepository_controller_test.go
Labels: dependencies

#1811 [RFC-0010] Link workload identity docs to complete guide
  docs/spec/v1/buckets.md
  docs/spec/v1/gitrepositories.md
  docs/spec/v1/ocirepositories.md
Labels: area/docs
