Repository fluxcd/source-controller, pull requests merged in 2025-04, with the labels that each got.

#1775 Update dependencies to Helm v3.17.3
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: dependencies

#1778 Add Mutual TLS support to `GitRepository`
  docs/spec/v1/gitrepositories.md
  go.mod
  go.sum
  internal/controller/gitrepository_controller_test.go
  internal/controller/testdata/certs/ca-key.pem
  internal/controller/testdata/certs/ca.csr
  internal/controller/testdata/certs/ca.pem
  internal/controller/testdata/certs/client-key.pem
  internal/controller/testdata/certs/client.csr
  internal/controller/testdata/certs/client.pem
  internal/controller/testdata/certs/server-key.pem
  internal/controller/testdata/certs/server.csr
  internal/controller/testdata/certs/server.pem
Labels: enhancement, area/git

#1774 Implement Sparse Checkout for `GitRepository`
  api/v1/gitrepository_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml
  docs/api/v1/source.md
  docs/spec/v1/gitrepositories.md
  internal/controller/gitrepository_controller.go
  internal/controller/gitrepository_controller_test.go
Labels: area/git, area/api

#1783 Update to Kubernetes 1.33.0 and Go 1.24.0
  .github/workflows/cifuzz.yaml
  .github/workflows/e2e.yaml
  .github/workflows/scan.yaml
  .github/workflows/tests.yaml
  .github/workflows/verify.yaml
  DEVELOPMENT.md
  Dockerfile
  Makefile
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  internal/controller/bucket_controller.go
  internal/controller/gitrepository_controller.go
  internal/controller/helmchart_controller.go
  internal/controller/helmchart_controller_test.go
  internal/controller/helmrepository_controller.go
  internal/controller/ocirepository_controller.go
  internal/controller/ocirepository_controller_test.go
  internal/reconcile/reconcile.go
  tests/fuzz/Dockerfile.builder
Labels: dependencies

#1785 Downgrade `Masterminds/semver` to v3.3.0
  go.mod
  go.sum
Labels: dependencies
